// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYPVW2YsbmF-3Zl2-u8qCCWmNqvvBKN0',
    appId: '1:103586095329:web:7cd531b6e217776b6e57a0',
    messagingSenderId: '103586095329',
    projectId: 'flash-chat-9666',
    authDomain: 'flash-chat-9666.firebaseapp.com',
    databaseURL: 'https://flash-chat-9666-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chat-9666.appspot.com',
    measurementId: 'G-FJ1SXCBBPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6YSPo2dJlFLgGtYofJ7i8oWdMdnLzsR0',
    appId: '1:103586095329:android:85a79a02429fcb2e6e57a0',
    messagingSenderId: '103586095329',
    projectId: 'flash-chat-9666',
    databaseURL: 'https://flash-chat-9666-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chat-9666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU6_PAwXp15J3FO4gERj8fOpZxY4Kjy2I',
    appId: '1:103586095329:ios:b6461943bb1a069b6e57a0',
    messagingSenderId: '103586095329',
    projectId: 'flash-chat-9666',
    databaseURL: 'https://flash-chat-9666-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chat-9666.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );
}
